# ecommerce_config.yaml
market_params:
  budget: 200000.0
  cpc_avg: 70.0
  cpc_stdev: 25.0
  scenarios_count: 500000

product_params:
  conversion_min: 0.015
  conversion_max: 0.035
  
  base_cogs: 1200.0
  tax_rate: 0.06
  
  repeat_purchases_min: 1.2
  repeat_purchases_max: 2.5
  
  avg_ticket_min: 4500
  avg_ticket_max: 12000