market_params:
  budget: 120000.0
  cpc_avg: 300.0
  cpc_stdev: 80.0
  scenarios_count: 500000

product_params:
  conversion_min: 0.005
  conversion_max: 0.025
  
  base_cogs: 50.0
  tax_rate: 0.06
  
  repeat_sessions_min: 3.0
  repeat_sessions_max: 24.0
  
  price_range_min: 990
  price_range_max: 4990